# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/cli.ipynb.

# %% auto 0
__all__ = ['CLI', 'main']

# %% ../src/cli.ipynb 2
import fire
from dataclasses import asdict
from .chains import get_chain
from .deposit import DepositQuote
from .withdraw import Withdrawal
from .helpers import ADDRESS_ZERO, normalize_address

# %% ../src/cli.ipynb 3
# Fire's literal_eval parses `0x...` as a hex int — unmangle before checksum/normalize.
def _addr(v): return v if v is None else normalize_address('0x' + format(v, '040x') if isinstance(v, int) else v)

def _new_pool_spec(c, token0, token1, pool_type, tick_spacing):
    t0, t1 = c.get_token(token0), c.get_token(token1)
    if t0 is None or t1 is None: raise SystemExit('token0 or token1 not known to Sugar')
    pool_type = str(pool_type).lower()
    if pool_type == 'cl':
        if tick_spacing is None: raise SystemExit('--pool-type cl requires --tick-spacing N')
        return c.pool_spec(t0, t1, tick_spacing=int(tick_spacing))
    if pool_type in ('stable', 'volatile'):
        if tick_spacing is not None: raise SystemExit('--tick-spacing is CL-only')
        return c.pool_spec(t0, t1, stable=(pool_type == 'stable'))
    raise SystemExit(f'invalid --pool-type: {pool_type} (expected cl/stable/volatile)')

def _resolve_pool(c, *, pool=None, token0=None, token1=None, pool_type=None, tick_spacing=None):
    """--pool ADDR (existing) XOR (--token0 --token1 --pool-type [--tick-spacing]) (new)."""
    pool, token0, token1 = _addr(pool), _addr(token0), _addr(token1)
    if pool is not None:
        if any(x is not None for x in (token0, token1, pool_type, tick_spacing)):
            raise SystemExit('--pool cannot be combined with --token0/--token1/--pool-type/--tick-spacing')
        p = c.get_pool_by_address(pool)
        if p is None: raise SystemExit(f'pool {pool} not found')
        return p
    if not token0 or not token1 or not pool_type:
        raise SystemExit('new pool requires --token0, --token1, and --pool-type {cl,stable,volatile}')
    return _new_pool_spec(c, token0, token1, pool_type, tick_spacing)

def _one_side(a0, a1, ctx):
    """Return the `amount_tokenN` kwarg for whichever side is set, raising if both/neither."""
    if (a0 is None) == (a1 is None): raise SystemExit(f'{ctx} requires exactly one of --amount0 / --amount1')
    return {'amount_token0': a0} if a0 is not None else {'amount_token1': a1}

def _build_quote(c, p, *, amount0, amount1, price_lower, price_upper, tick_lower, tick_upper, initial_price):
    """Resolve a DepositQuote for either basic or CL, new or existing pool."""
    is_new = p.lp == ADDRESS_ZERO
    a0 = p.token0.parse_units(float(amount0)) if amount0 is not None else None
    a1 = p.token1.parse_units(float(amount1)) if amount1 is not None else None
    if p.is_cl:
        kwargs = _one_side(a0, a1, 'CL deposit')
        if is_new and initial_price is None: raise SystemExit('new CL pool requires --initial-price')
        if initial_price is not None: kwargs['initial_price'] = float(initial_price)
        if tick_lower is not None or tick_upper is not None:
            kwargs['tick_lower'], kwargs['tick_upper'] = tick_lower, tick_upper
        else:
            kwargs['price_lower'] = float(price_lower) if price_lower is not None else None
            kwargs['price_upper'] = float(price_upper) if price_upper is not None else None
        return c.quote_concentrated_deposit(p, **kwargs)
    if any(x is not None for x in (price_lower, price_upper, tick_lower, tick_upper, initial_price)):
        raise SystemExit('basic deposits do not accept CL flags')
    if is_new:
        if a0 is None or a1 is None: raise SystemExit('new basic pool requires both --amount0 and --amount1')
        return DepositQuote(pool=p, amount_token0=a0, amount_token1=a1)
    return c.quote_basic_deposit(p, **_one_side(a0, a1, 'existing basic pool deposit'))
def _position_dict(p):
    """Compact dict for CLI output: asdict + overrides for the pool and amount fields."""
    t0, t1 = p.pool.token0, p.pool.token1
    return {**asdict(p),
            'pool': {'symbol': p.pool.symbol, 'lp': p.pool.lp, 'is_cl': p.pool.is_cl},
            'amount_token0': t0.to_float(p.amount_token0), 'amount_token1': t1.to_float(p.amount_token1),
            'staked_token0': t0.to_float(p.staked_token0), 'staked_token1': t1.to_float(p.staked_token1),
            'unstaked_earned0': t0.to_float(p.unstaked_earned0), 'unstaked_earned1': t1.to_float(p.unstaked_earned1)}

def _find_position(c, *, pool=None, position=None):
    """Find a wallet position. Identify by --position (CL) or --pool (basic; uses id=0)."""
    pool = _addr(pool)
    if pool is None and position is None:
        raise SystemExit('withdraw requires --pool (basic) or --position (CL)')
    tid = int(position) if position is not None else 0
    match = next((p for p in c.get_positions() if p.id == tid and (pool is None or p.pool.lp.lower() == pool.lower())), None)
    if match is None: raise SystemExit('position not found')
    return match

# %% ../src/cli.ipynb 4
class CLI:
    """Sugar SDK command-line interface.

    Default is dry-run (no broadcast). Pass --broadcast to send the tx.
    Amounts are human-readable (e.g. `0.5` → `0.5 * 10^decimals`).
    `--chain` takes a numeric chain id (10, 8453, 130, 1135).

    Examples:
        # preview a basic deposit
        python -m sugar deposit --chain=10 --pool=0xd25711... --amount0=0.0001 --amount1=1

        # list wallet positions
        python -m sugar positions --chain=10

        # withdraw 50% of a basic position
        python -m sugar withdraw --chain=10 --pool=0xd25711... --fraction=0.5 --broadcast"""

    def deposit(self, *, chain: int, pool: str = None,
                token0: str = None, token1: str = None, pool_type: str = None, tick_spacing=None,
                amount0=None, amount1=None,
                price_lower=None, price_upper=None, tick_lower=None, tick_upper=None,
                initial_price=None, slippage: float = 0.01, deadline_minutes: float = 30,
                broadcast: bool = False):
        """Deposit liquidity. Dry-run returns unsigned tx(s); --broadcast returns the receipt."""
        with get_chain(str(chain), threading_max_workers=1) as c:
            p = _resolve_pool(c, pool=pool, token0=token0, token1=token1,
                              pool_type=pool_type, tick_spacing=tick_spacing)
            q = _build_quote(c, p, amount0=amount0, amount1=amount1,
                             price_lower=price_lower, price_upper=price_upper,
                             tick_lower=tick_lower, tick_upper=tick_upper,
                             initial_price=initial_price)
            r = c.deposit(q, delay_in_minutes=deadline_minutes, slippage=slippage, dry_run=not broadcast)
            if not broadcast: return r
            return {'tx': r.transactionHash.hex(), 'status': r.status, 'gas': r.gasUsed, 'block': r.blockNumber}

    def positions(self, *, chain: int, owner: str = None):
        """List positions for `--owner` (defaults to the SUGAR_PK wallet)."""
        with get_chain(str(chain), threading_max_workers=1) as c:
            return [_position_dict(p) for p in c.get_positions(_addr(owner))]

    def withdraw(self, *, chain: int, pool: str = None, position: int = None,
                 fraction: float = 1.0, burn: bool = False, collect: bool = True,
                 unwrap_native: bool = False, slippage: float = 0.01,
                 deadline_minutes: float = 30, broadcast: bool = False):
        """Withdraw a position. Identify by --pool (basic) or --position (CL). Default --fraction=1.0."""
        with get_chain(str(chain), threading_max_workers=1) as c:
            p = _find_position(c, pool=pool, position=position)
            w = Withdrawal.from_position(p, fraction=float(fraction), burn=burn)
            r = c.withdraw(w, delay_in_minutes=deadline_minutes, slippage=slippage,
                           collect=collect, unwrap_native=unwrap_native, dry_run=not broadcast)
            if not broadcast: return r
            return {'tx': r.transactionHash.hex(), 'status': r.status, 'gas': r.gasUsed, 'block': r.blockNumber}

    def stake(self, *, chain: int, pool: str = None, position: int = None, broadcast: bool = False):
        """Stake an unstaked position into the pool's gauge."""
        with get_chain(str(chain), threading_max_workers=1) as c:
            p = _find_position(c, pool=pool, position=position)
            r = c.stake(p, dry_run=not broadcast)
            if not broadcast: return r
            return {'tx': r.transactionHash.hex(), 'status': r.status, 'gas': r.gasUsed, 'block': r.blockNumber}

    def unstake(self, *, chain: int, pool: str = None, position: int = None,
                amount: int = None, broadcast: bool = False):
        """Unstake from the pool's gauge. CL: full only. Basic: pass --amount for partial."""
        with get_chain(str(chain), threading_max_workers=1) as c:
            p = _find_position(c, pool=pool, position=position)
            r = c.unstake(p, amount=amount, dry_run=not broadcast)
            if not broadcast: return r
            return {'tx': r.transactionHash.hex(), 'status': r.status, 'gas': r.gasUsed, 'block': r.blockNumber}

    def claim_emissions(self, *, chain: int, pool: str = None, position: int = None, broadcast: bool = False):
        """Claim gauge emissions for a staked position."""
        with get_chain(str(chain), threading_max_workers=1) as c:
            p = _find_position(c, pool=pool, position=position)
            r = c.claim_emissions(p, dry_run=not broadcast)
            if not broadcast: return r
            return {'tx': r.transactionHash.hex(), 'status': r.status, 'gas': r.gasUsed, 'block': r.blockNumber}

    def claim_fees(self, *, chain: int, pool: str = None, position: int = None,
                   burn: bool = False, unwrap_native: bool = False, broadcast: bool = False):
        """Claim LP fees. CL: NFPM multicall (collect + optional unwrap/burn). Basic: pool.claimFees()."""
        with get_chain(str(chain), threading_max_workers=1) as c:
            p = _find_position(c, pool=pool, position=position)
            r = c.claim_fees(p, burn=burn, unwrap_native=unwrap_native, dry_run=not broadcast)
            if not broadcast: return r
            return {'tx': r.transactionHash.hex(), 'status': r.status, 'gas': r.gasUsed, 'block': r.blockNumber}

# %% ../src/cli.ipynb 5
def main():
    from dotenv import load_dotenv
    load_dotenv()
    fire.Fire(CLI)
