# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/deposit.ipynb.

# %% auto 0
__all__ = ['DepositQuote']

# %% ../src/deposit.ipynb 2
from dataclasses import dataclass
from typing import Optional
from .pool import LiquidityPool

# %% ../src/deposit.ipynb 3
# NOTE: for CL pools, `pool.type` is the tick spacing (Sugar's convention).

@dataclass(frozen=True)
class DepositQuote:
    """Returned by `chain.quote_*_deposit` and accepted by `chain.deposit`.

    CL fields (`tick_lower`, `tick_upper`, `sqrt_price_x96`) are required when
    `pool.is_cl`, must stay at defaults otherwise. `sqrt_price_x96` is set by
    the SDK from `initial_price` — consumers don't compute it themselves.
    """
    pool: LiquidityPool
    amount_token0: int
    amount_token1: int
    # CL-only fields
    tick_lower: Optional[int] = None
    tick_upper: Optional[int] = None
    # Q64.96 sqrt(P); used by NFPM only when initializing an uninitialized pool. SDK-computed.
    sqrt_price_x96: int = 0

    def __post_init__(self):
        if self.pool.is_cl:
            if self.tick_lower is None or self.tick_upper is None:
                raise ValueError("CL DepositQuote requires tick_lower and tick_upper")
            if self.tick_lower >= self.tick_upper:
                raise ValueError("tick_lower must be < tick_upper")
            ts = self.pool.type
            if self.tick_lower % ts != 0 or self.tick_upper % ts != 0:
                raise ValueError(f"tick bounds must be multiples of tick spacing ({ts})")
        else:
            if self.tick_lower is not None or self.tick_upper is not None or self.sqrt_price_x96 != 0:
                raise ValueError("basic DepositQuote must not set tick / sqrt_price_x96 fields")
