# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/swap.ipynb.

# %% auto 0
__all__ = ['FLAG_ALLOW_REVERT', 'ABI_DEFINITION', 'CONTRACT_BALANCE_FOR_V3_SWAPS', 'CommandType', 'BridgeType', 'RoutePlanner',
           'setup_planner', 'SuperSwapQuote', 'SuperSwapDataInput', 'SuperSwapData', 'build_super_swap_data']

# %% ../src/swap.ipynb 3
from dataclasses import dataclass
from .quote import Quote, pack_path
from .helpers import apply_slippage, ICACallData, hash_ICA_calls, to_bytes32, to_bytes32_str
from .helpers import ADDRESS_ZERO, normalize_address
from .token import Token
from .pool import LiquidityPoolForSwap
from enum import IntEnum
from typing import List, Any, Tuple, Optional
from eth_abi import encode
from eth_abi.packed import encode_packed
from web3 import Web3
from .abi import get_abi


# %% ../src/swap.ipynb 4
class CommandType(IntEnum):
    V3_SWAP_EXACT_IN = 0x00
    V3_SWAP_EXACT_OUT = 0x01
    SWEEP = 0x04
    V2_SWAP_EXACT_IN = 0x08
    V2_SWAP_EXACT_OUT = 0x09
    WRAP_ETH = 0x0b
    UNWRAP_WETH = 0x0c
    TRANSFER_FROM = 0x07
    BRIDGE_TOKEN = 0x12
    EXECUTE_CROSS_CHAIN = 0x13
    EXECUTE_SUB_PLAN = 0x21

class BridgeType(IntEnum):
    """
    Enum for different bridge types.
    """
    HYP_XERC20 = 0x01
    XVELO = 0x02

FLAG_ALLOW_REVERT = 0x80

# Define ABI types for each command
ABI_DEFINITION = {
    CommandType.V3_SWAP_EXACT_IN: [
        "address", # recipient
        "uint256", # amountIn
        "uint256", # amountOutMin
        "bytes", # path
        "bool", # payerIsUser
        "bool"  # isUni
    ],
    CommandType.V2_SWAP_EXACT_IN: [
        "address",
        "uint256",
        "uint256",
        "(address,address,bool)[]",
        "bool",
        "bool"  # isUni
    ],
    CommandType.V2_SWAP_EXACT_OUT: [
        "address",
        "uint256",
        "uint256",
        "(address,address,bool)[]",
        "bool",
        "bool"  # isUni
    ],
    CommandType.V3_SWAP_EXACT_OUT: [
        "address",
        "uint256",
        "uint256",
        "bytes",
        "bool",
        "bool"  # isUni
    ],
    CommandType.WRAP_ETH: [
        "address",
        "uint256"
    ],
    CommandType.UNWRAP_WETH: [
        "address",
        "uint256"
    ],
    CommandType.SWEEP: [
        "address",
        "address",
        "uint256"
    ],
    CommandType.TRANSFER_FROM: [
        "address",  # sender
        "address",  # recipient
        "uint256"   # amount
    ],
    CommandType.BRIDGE_TOKEN: [
        "uint8",    # bridgeType
        "address",  # recipient
        "address",  # token
        "address",  # bridge
        "uint256",  # amount
        "uint256",  # msgFee
        "uint32",   # domain
        "bool"      # payerIsUser
    ],
    CommandType.EXECUTE_SUB_PLAN: [
        "bytes",    
        "bytes[]"
    ],
    CommandType.EXECUTE_CROSS_CHAIN: [
        "uint32",   # domain
        "address",  # icaRouter
        "bytes32",  # remoteRouter
        "bytes32",  # ism
        "bytes32",  # commitment
        "uint256",  # msgFee
        "address",  # hook
        "bytes"
    ]
}

class RoutePlanner:
    def __init__(self):
        """Initialize a new RoutePlanner"""
        self.commands = "0x"
        self.inputs: List[bytes] = []
        self.bytes_commands: List[bytes] = []

    def add_command(self, command_type: CommandType, parameters: List[Any], allow_revert = False) -> None:
        """
        Add a command to the route planner
        
        Args:
            command_type: Type of command to add
            parameters: Parameters for the command
        """
        # Get the ABI definition for this command
        abi_types = ABI_DEFINITION[command_type]
        self.inputs.append(encode(abi_types, parameters))
        # Add command byte to commands
        command_type = command_type | FLAG_ALLOW_REVERT if allow_revert else command_type
        command_hex = format(command_type, '02x')
        self.commands = self.commands + command_hex
        # TODO: figure out why we keep this alongside command_hex
        self.bytes_commands.append(format(command_type, '02x'))

    def get_encoded_commands(self) -> str: return self.commands
    
    def get_encoded_inputs(self) -> List[bytes]: return self.inputs

    # using this for testing
    def get_pretty_encoded_inputs(self) -> List[str]: return list(map(lambda i: "0x" + i.hex(), self.get_encoded_inputs())) 

# %% ../src/swap.ipynb 6
# Constants
CONTRACT_BALANCE_FOR_V3_SWAPS = int("0x8000000000000000000000000000000000000000000000000000000000000000", 16)

def setup_planner(quote: Quote, slippage: float, account: str, router_address: str) -> RoutePlanner:
    """Setup route planner with the given quote and chain"""
    
    route_planner = RoutePlanner()
    min_amount_out = apply_slippage(quote.amount_out, slippage)

    # By default money comes from contract
    tokens_come_from_contract = False
    
    # Handle wrapped native token if needed
    if quote.from_token.wrapped_token_address:
        # When trading from native token, wrap token first
        route_planner.add_command(CommandType.WRAP_ETH, [router_address, quote.amount_in])
        tokens_come_from_contract = True
    
    # Group nodes by pool type (v2 or v3)
    grouped_nodes: List[List[Tuple[LiquidityPoolForSwap, bool]]] = []

    for node in quote.path:
        if not grouped_nodes: grouped_nodes.append([node])
        elif node[0].type < 1:
            # Current node is a v2 pool
            if float(grouped_nodes[-1][0][0].type) < 1: grouped_nodes[-1].append(node)
            else: grouped_nodes.append([node])
        else:
            # Current node is a v3 pool
            if grouped_nodes[-1][0][0].type >= 1: grouped_nodes[-1].append(node)
            else: grouped_nodes.append([node])
    
    if len(grouped_nodes) == 1:
        # All nodes belong to the same pool type
        nodes = grouped_nodes[0]
        is_v2_pool = float(nodes[0][0].type) < 1
        
        route_planner.add_command(
            CommandType.V2_SWAP_EXACT_IN if is_v2_pool else CommandType.V3_SWAP_EXACT_IN,
            [
                # Where should money go?
                router_address if quote.to_token.wrapped_token_address else account,
                quote.amount_in,
                min_amount_out,
                pack_path(nodes, for_swap=True).encoded,
                not tokens_come_from_contract,
                False, # isUni
            ]
        )
    else:
        # Mixed v2 and v3 pools
        first_batch = grouped_nodes[0]
        last_batch = grouped_nodes[-1]
        rest = grouped_nodes[1:-1]
        
        # Handle first batch
        is_first_batch_v2 = not first_batch[0][0].is_cl
        next_batch = rest[0] if rest else last_batch
        
        route_planner.add_command(
            CommandType.V2_SWAP_EXACT_IN if is_first_batch_v2 else CommandType.V3_SWAP_EXACT_IN,
            [
                router_address if is_first_batch_v2 else next_batch[0][0].lp,
                quote.amount_in,
                0,  # No expectations on min amount out for first batch
                pack_path(first_batch, for_swap=True).encoded,
                not tokens_come_from_contract,
                False,  # isUni
            ]
        )
        
        # Handle middle batches
        for idx, batch in enumerate(rest):
            is_batch_v2 = not batch[0][0].is_cl
            next_batch = rest[idx + 1] if idx + 1 < len(rest) else last_batch
            
            route_planner.add_command(
                CommandType.V2_SWAP_EXACT_IN if is_batch_v2 else CommandType.V3_SWAP_EXACT_IN,
                [
                    router_address if is_batch_v2 else next_batch[0][0].lp,
                    0 if is_batch_v2 else CONTRACT_BALANCE_FOR_V3_SWAPS,
                    0,  # No expectations for middle batches
                    pack_path(batch, for_swap=True).encoded,
                    False,  # Money comes from contract
                    False,  # isUni
                ]
            )
        
        # # Handle last batch
        is_last_batch_v2 = not last_batch[0][0].is_cl
        
        route_planner.add_command(
            CommandType.V2_SWAP_EXACT_IN if is_last_batch_v2 else CommandType.V3_SWAP_EXACT_IN,
            [
                router_address if quote.to_token.wrapped_token_address else account,
                0 if is_last_batch_v2 else CONTRACT_BALANCE_FOR_V3_SWAPS,
                min_amount_out,
                pack_path(last_batch, for_swap=True).encoded,
                False,  # Money comes from contract
                False,  # isUni
            ]
        )
    
    # Handle unwrapping WETH if needed
    if quote.to_token.wrapped_token_address: route_planner.add_command(CommandType.UNWRAP_WETH, [account, min_amount_out])
    
    return route_planner

# %% ../src/swap.ipynb 8
@dataclass(frozen=True)
class SuperSwapQuote:
    from_token: Token
    to_token: Token
    from_bridge_token: Token
    to_bridge_token: Token
    amount_in: float
    origin_quote: Optional[Quote] = None
    destination_quote: Optional[Quote] = None

@dataclass(frozen=True)
class SuperSwapDataInput:
    from_token: Token
    to_token: Token
    from_bridge_token: Token
    to_bridge_token: Token
    account: str
    user_ICA: str
    user_ICA_balance: int
    origin_domain: int
    origin_bridge: str
    origin_hook: str
    origin_ICA_router: str
    destination_ICA_router: str
    destination_router: str
    destination_domain: int
    slippage: float
    bridged_amount: int
    swapper_contract_addr: str
    destination_quote: Optional[Quote]
    salt: str
    bridge_fee: int 
    xchain_fee: int

@dataclass(frozen=True)
class SuperSwapData: destination_planner: RoutePlanner; calls: List[ICACallData]; origin_domain: int; salt: str; needs_relay: bool 

# %% ../src/swap.ipynb 10
def build_super_swap_data(input: SuperSwapDataInput) -> SuperSwapData:
    d_quote, account, slippage, swap_contract_addr = input.destination_quote, input.account, input.slippage, input.swapper_contract_addr

    destination_chain_swap_plan = setup_planner(d_quote, slippage, account, swap_contract_addr) if d_quote else None

    # TODO: figure out if we can just use len(commands) here
    swap_subplan_cmds = destination_chain_swap_plan.get_encoded_commands() if destination_chain_swap_plan else None
    swap_subplan_cmds = bytes.fromhex(swap_subplan_cmds.replace('0x', '')) if swap_subplan_cmds else None

    # Encode fallback transfer
    transfer_subplan = encode_packed(["bytes1"], [bytes([CommandType.TRANSFER_FROM])])

    print(f">>>>>>>>>>>>>> transfer_subplan >>>>>>>>>>>>>>>", transfer_subplan.hex())

    transfer_args = encode(
        ABI_DEFINITION[CommandType.TRANSFER_FROM],
        [input.to_bridge_token.token_address, account, CONTRACT_BALANCE_FOR_V3_SWAPS]
    )

    print(f">>>>>>>>>>>>>> transfer_args >>>>>>>>>>>>>>>", transfer_args.hex())
    print(f">>>>>>>>>>>>>>> original swap_subplan_cmds", swap_subplan_cmds)

    subplan_abi = ["bytes", "bytes[]"]

    print(f">>>>>>>>>>>>>> subplan_abi >>>>>>>>>>>>>>>", subplan_abi)
    print(f">>>>>>>>>>>>>> swap_subplan_cmds >>>>>>>>>>>>>>>", swap_subplan_cmds.hex() if swap_subplan_cmds else None)

    destination_inputs = [
        encode(subplan_abi, [swap_subplan_cmds, destination_chain_swap_plan.inputs]),
        encode(subplan_abi, [transfer_subplan, [transfer_args]]),
    ] if swap_subplan_cmds else None

    # Encode Sub Plan commands
    destination_cmds = encode_packed(
        ["bytes", "bytes"],
        [
            bytes([CommandType.EXECUTE_SUB_PLAN | FLAG_ALLOW_REVERT]), 
            bytes([CommandType.EXECUTE_SUB_PLAN | FLAG_ALLOW_REVERT])
        ]
    )

    print(f">>>>>>>>>>>>>> destination_cmds >>>>>>>>>>>>>>>", destination_cmds.hex())

    erc20_abi = [
        {
            "name": "approve",
            "type": "function",
            "inputs": [
                {"name": "spender", "type": "address"},
                {"name": "amount", "type": "uint256"}
            ],
            "outputs": [{"name": "", "type": "bool"}]
        }
    ]
    
    calls = [
        ICACallData(
            to=to_bytes32_str(input.to_bridge_token.token_address),
            value=0,
            # TODO: change this to maxBridgedAmount, as at least for exact-in we might not know exactly how much is bridged over, and want to be sure
            data=Web3().eth.contract(abi=erc20_abi).encode_abi("approve", args=[input.destination_router, input.user_ICA_balance + input.bridged_amount])
        )
    ]

    if destination_inputs:
        print(f">>>>>>>>>>>>>> destination_inputs >>>>>>>>>>>>>>>", destination_inputs)
        print(f">>>>>>>>>>>>> destination_router", input.destination_router)
        calls.append(ICACallData(
            to=to_bytes32_str(input.destination_router),
            value=0,
            data=Web3().eth.contract(abi=get_abi("swapper")).encode_abi("execute", args=[destination_cmds, destination_inputs])
        ))

    print(f"calls", calls)


    commitment_hash = hash_ICA_calls(calls, input.salt)

    print(f">>>>>>>>>>>>>>>>>>>>>>>>>>>> commitment_hash", commitment_hash.hex())

    needs_relay = input.to_token.token_address != input.to_bridge_token.token_address

    destination_chain_planner = RoutePlanner()

    # bridge command
    destination_chain_planner.add_command(CommandType.BRIDGE_TOKEN, [
        BridgeType.HYP_XERC20,
        input.user_ICA if needs_relay else input.account,
        input.from_bridge_token.token_address,
        input.origin_bridge,
        input.bridged_amount,
        input.bridge_fee,
        input.destination_domain,
        input.from_token.token_address == input.from_bridge_token.token_address,
    ])

    if needs_relay:
        # destination swap command
        destination_chain_planner.add_command(CommandType.EXECUTE_CROSS_CHAIN, [
            input.destination_domain,
            input.origin_ICA_router,
            to_bytes32(input.destination_ICA_router),
            to_bytes32(ADDRESS_ZERO),
            commitment_hash,
            # fee to dispatch x-chain message
            input.xchain_fee,
            input.origin_hook,
            # TODO: figure out if this works correctly
            bytes.fromhex("0x".replace('0x', ''))
        ])

    return SuperSwapData(destination_planner=destination_chain_planner, calls=calls, origin_domain=input.origin_domain, salt=input.salt, needs_relay=needs_relay)
