# AUTOGENERATED! DO NOT EDIT! File to edit: ../src/withdraw.ipynb.

# %% auto 0
__all__ = ['Withdrawal']

# %% ../src/withdraw.ipynb 2
from dataclasses import dataclass
from typing import Optional
from .pool import LiquidityPool
from .position import Position

# %% ../src/withdraw.ipynb 3
@dataclass(frozen=True)
class Withdrawal:
    """Input to `chain.withdraw`. Built from a `Position` via `Withdrawal.from_position`;
    Sugar's positions reader already provides current-price amounts so no on-chain quote
    step is needed."""
    pool: LiquidityPool
    # LP tokens to burn (basic) / liquidity to decrease (CL)
    liquidity: int
    # expected amounts out; slippage min computed at execution
    amount_token0: int
    amount_token1: int
    # CL only — the NFT tokenId
    token_id: Optional[int] = None
    # CL only — when True, append nfpm.burn(token_id) to the multicall to clean up the empty NFT
    burn: bool = False

    def __post_init__(self):
        if self.pool.is_cl and self.token_id is None:
            raise ValueError("CL Withdrawal requires token_id")
        if not self.pool.is_cl and self.token_id is not None:
            raise ValueError("basic Withdrawal must not set token_id")
        if self.liquidity <= 0: raise ValueError("liquidity must be positive")
        if self.burn and not self.pool.is_cl: raise ValueError("burn is CL-only")

    @classmethod
    def from_position(cls, position: Position, *, fraction: float = 1.0, burn: bool = False) -> "Withdrawal":
        """Linear scaling: `liquidity_out = position.liquidity * fraction`. Raw token amounts
        come from Sugar's snapshot (`position.amount_token0/1`); slippage on `chain.withdraw`
        protects against price drift between snapshot and execution.

        `burn=True` requires `fraction=1.0` — partial closes can't burn since liquidity remains
        on the NFT. `fraction=1.0` short-circuits the float multiplication for exact integer
        liquidity (important for very large V3 L values)."""
        if not 0 < fraction <= 1: raise ValueError("fraction must be in (0, 1]")
        if burn and fraction != 1.0: raise ValueError("burn requires fraction=1.0 (full close)")
        if position.liquidity == 0: raise ValueError("position has no liquidity to withdraw")
        if fraction == 1.0:
            liquidity, a0, a1 = position.liquidity, position.amount_token0, position.amount_token1
        else:
            liquidity = int(position.liquidity * fraction)
            if liquidity == 0: raise ValueError("fraction too small: computed liquidity is 0")
            a0 = int(position.amount_token0 * fraction)
            a1 = int(position.amount_token1 * fraction)
        return cls(
            pool=position.pool, liquidity=liquidity,
            amount_token0=a0, amount_token1=a1,
            token_id=position.id if position.is_cl else None,
            burn=burn,
        )
