on:  [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUGAR_PK: ${{ secrets.SUGAR_PK }}
      SUGAR_RPC_URI_10: ${{ secrets.SUGAR_RPC_URI_10 }}
      SUGAR_RPC_URI_8453: ${{ secrets.SUGAR_RPC_URI_8453 }}
      SUPERSIM_RPC_URL_BASE: ${{ secrets.SUPERSIM_RPC_URL_BASE }}
      SUPERSIM_RPC_URL_OP: ${{ secrets.SUPERSIM_RPC_URL_OP }}

    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Confirm forge is installed
        run: forge --version
      - name: Install supersim
        run: brew install ethereum-optimism/tap/supersim
      - name: Confirm supersim is installed
        run: supersim --version
      - name: Fork
        run: |
          supersim fork  --l2.host=0.0.0.0 --l2.starting.port=4444 --chains=op,base > /dev/null 2>&1 &
          sleep 10
      - name: Test fork
        run: cast call 0x7F6D3A4c8a1111DDbFe282794f4D608aB7Cb23A2 "MAX_TOKENS()(uint256)" --rpc-url http://localhost:4444
      - uses: fastai/workflows/nbdev-ci@master
